name: Publish github pages

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "package.json"
      - "README.md"
      - "webpack.config.script.js"
      - ".babelrc"

jobs:
  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
      - run: npm run javascript:production
      - name: Deploy Github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
